packages:
  # include packages in subfolders (change as required)
  - 'app/**'
  - 'breejob/**'
  - 'emailserver/**'
  - 'filewatcherlocal/**'
  # exclude packages that are inside test directories
  - '!**/test/**'
